### ISSUE TITLE
Indicate language in code snippets

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1049]
Initially from #1002.

@hzoo :
> Also it think it for differentiating the snippets maybe we could add some css to the code frame to signify which language it is? (based on the css class language-js, etc)

<img width="708" alt="cefeef40-b168-11e6-878d-dcad90d3d208" src="https://cloud.githubusercontent.com/assets/1493671/20967298/00dad6ac-bc7f-11e6-8bef-51b6376648a4.png">

We could inject it using CSS based on the classname of the code block.

![code-blocks-deo](https://cloud.githubusercontent.com/assets/1493671/20967379/7ad88760-bc7f-11e6-80c2-f1a4e578f603.png)

**Comment by raspo** [comment]
I can work on PR for this.
Here is a proof of concept hacked together with the inspector. 
The header is inspired by what can be found on the [react docs](https://facebook.github.io/react/docs/state-and-lifecycle.html).

<img width="895" alt="screen shot 2016-12-07 at 12 56 07 pm" src="https://cloud.githubusercontent.com/assets/927264/20986237/9c1487d8-bc7c-11e6-82e1-cf3d1cfb06db.png">

```css
div.highlighter-rouge:before {
    content: 'blah';
    display: block;
    height: 18px;
    line-height: 18px;
    background: #fbf4d0;
    font-size: 12px;
    font-weight: bold;
    padding: 0 10px;
    color: #b0a673;
}

.language-js.highlighter-rouge:before,
.language-javascript.highlighter-rouge:before {
    content: 'Javascript';
}

.language-sh.highlighter-rouge:before {
    content: 'Shell';
}
```

We could even consider making the "header" a big bigger and move the copy button to the top-right.
Thoughts?
