### ISSUE TITLE
Deep linking CSS causing unclickable links above header

### ISSUE THREAD

**Issue by thecotne** [babel/babel.github.io#251]
on this page https://babeljs.io/docs/using-babel/#require-hook
text "For full documentation on the Babel CLI see the usage docs."
is not clickable and selectable

because of this css

![capture](https://cloud.githubusercontent.com/assets/1606993/7327486/a21345b4-eade-11e4-8cbf-03d7927e9fd3.PNG)

**Comment by thejameskyle** [comment]
This is done to keep the scroll to `#hash` linking from hiding the title behind the navbar, I'll have to find a better way to do this

**Comment by thecotne** [comment]
```css
h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6 {
    position: relative;
    z-index: -1;
}
```
`z-index: -1` fixes issue
