### ISSUE TITLE
Github Pages: Update to kramdown (markdown engine) from redcarpet

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#709]
### :grey_question: Issue

We are currently using the **redcarpet** markdown plugin for Github Pages (which we use to build out the website) and we need to update to **kramdown**.

EDIT: github has a small guide too https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/

> If you need help, an idea I just thought of was to [search](https://github.com/search?q=redcarpet+kramdown&ref=searchresults&state=closed&type=Issues&utf8=%E2%9C%93) for the same issue on github since all github page repos will need to update to kramdown by May.

> An example I found just searching around was https://github.com/itsmrwave/systematic-theology/pull/2/files

Currently, we get an email each time we commit that says something like:

> The page build completed successfully, but returned the following warning:

> You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

So we want to update our redcarpet plugin to be kramdown instead and much sure the site still loads correctly (wherever we use markdown to render).

### :dart: Goal

Replace redcarpet (and it's associated plugins or features) with **kramdown** with the site still working as expected. You could include some screenshots in the PR as well (Although we would run this PR locally to check before merging).

> If you aren't able to get all the extensions from working (meaning can't find an equivalent), we can finish up the PR from there.

#### :sparkles: Bonus
If anyone is willing, we might also want to update the kramdown version in [Gemfile.lock](https://github.com/babel/babel.github.io/blob/master/Gemfile.lock#L43)

### :clipboard: Step by Step
- [ ] claim this issue (comment below)
- [ ] Setup repository locally https://github.com/babel/babel.github.io#setup.
  - This basically just includes cloning the repo, using make to setup, and then opening up the local website on localhost.
- [ ] Edit the [_config.yml](_config.yml) file. The relevant lines (as far as I can tell) are [here](https://github.com/babel/babel.github.io/blob/master/_config.yml#L12-L21) where it describes the markdown plugin and extensions.

```
// Something I found from http://idratherbewriting.com/2016/02/21/bug-with-kramdown-and-rouge-with-github-pages/
// before from redcarpet + pygments
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]
Just change it to this:

// after with kramdown + route
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
```

- [ ] Test the changes locally (I would check out various pages like the homepage, the learn es2015 page for anything weird/different from what's on the current site. This is regarding the markdown rendering so you might need to do some additional configuration changes.
- [ ] Commit the change. We don't have particular commit convention, but doing something like `Build: update _config.yml to build markdown with kramdown instead of redcarpet.
- [ ] Start a Pull Request
 (If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request).
  - Like mentioned above, free feel to include a screenshot to show that the site is still working.
- [ ] Done (Comment below to ask for a review) - Then we can give it a :+1: and merge.
